apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/persistentvolumeclaim.yaml
  - manifests/configmap.yaml
  - manifests/statefulset.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/service2.yaml
  - manifests/backendService.yaml
  - manifests/CronJob.yaml


images:
  - name: PROJECT/FETCHAPP
    newName: misetius/fetchapp
    newTag: "4.6"

  - name: PROJECT/BACKEND
    newName: misetius/cloud
    newTag: "3.6"